version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_gestao
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19101969
      POSTGRES_DB: gestao_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
